kind: Service
apiVersion: v1
metadata:
  name: k3d-react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: k3d-react-app